---

- name: Dashboards Install | Create opensearch dashboard user
  ansible.builtin.user:
    name: "{{ os_dashboards_user }}"
    state: present
    shell: /bin/false
    create_home: true
    home: "{{ os_dashboards_home }}"

- name: Dashboards Install | Create home directory
  ansible.builtin.file:
    path: "{{ os_dashboards_home }}"
    state: directory
    owner: "{{ os_dashboards_user }}"
    group: "{{ os_dashboards_user }}"

- name: Dashboards Install | Download opensearch dashbaord {{ os_dashboards_version }}
  ansible.builtin.get_url:
    url: "{{ os_dashboards_download_url }}/{{ os_dashboards_version }}/opensearch-dashboards-{{ os_dashboards_version }}-linux-x64.tar.gz"
    dest: "/tmp/opensearch-dashboards.tar.gz"

- name: Dashboards Install | Extract the tar file
  ansible.builtin.unarchive:
    src: "/tmp/opensearch-dashboards.tar.gz"
    dest: "{{ os_dashboards_home }}"
    extra_opts:
      - --strip-components=1
    remote_src: true

- name: Dashboards Install | Copy Configuration File
  ansible.builtin.template:
    src: opensearch_dashboards.yml.j2
    dest: "{{ os_dashboards_conf_dir }}/opensearch_dashboards.yml"
    owner: "{{ os_dashboards_user }}"
    group: "{{ os_dashboards_user }}"
    mode: 0644
    backup: true

- name: Dashboards Install | Set the file ownerships
  ansible.builtin.file:
    dest: "{{ os_dashboards_home }}"
    owner: "{{ os_dashboards_user }}"
    group: "{{ os_dashboards_user }}"
    recurse: true

- name: Dashboards Install | Set the folder permission
  ansible.builtin.file:
    dest: "{{ os_dashboards_conf_dir }}"
    owner: "{{ os_dashboards_user }}"
    group: "{{ os_dashboards_user }}"
    mode: 0700

- name: Dashboards Install | Copy certificate to dashboard node
  ansible.builtin.copy:
    src: "{{ os_local_certs_path }}/{{ opensearch_hostname }}_http.{{ item }}"
    dest: "{{ os_dashboards_conf_dir }}/dashboards.{{ item }}"
    owner: "{{ os_dashboards_user }}"
    group: "{{ os_dashboards_user }}"
    mode: 0600
  with_items: ["key", "pem"]
  when: os_dashboards_use_opensearch_certs

- name: Dashboards Install | create systemd service
  ansible.builtin.template:
    src: dashboards.service.j2
    dest: "{{ os_dashboards_systemctl_path }}/dashboards.service"

- name: Make sure opensearch dashboards is started
  ansible.builtin.service:
    name: dashboards
    state: started
    enabled: true