---

- name: Disable the selinux
  ansible.posix.selinux:
    state: disabled
  when:
    - ansible_distribution != "Ubuntu"
    - ansible_distribution != "Amazon"

- name: Set open files limit in sysctl.conf
  ansible.posix.sysctl:
    name: fs.file-max
    value: 65536

- name: Include dashboards installation
  ansible.builtin.import_tasks: 
    file: 01_install.yml

- name: Include checks
  ansible.builtin.import_tasks: 
    file: 02_checks.yml
