---
#
# Last Changes:
# Wolfgang Hotwagner updated this file on 23. April 2024
#

# Disabling for Amazon Linux 2 as selinux is disabled by default.
- name: Disable the selinux
  ansible.posix.selinux:
    state: disabled
  when: (ansible_distribution != "Ubuntu") and (ansible_distribution != "Amazon")

- name: Tune the system settings
  ansible.builtin.import_tasks: tune.yml

- name: Include dashboards installation
  ansible.builtin.import_tasks: dashboards.yml

- name: Include tests
  ansible.builtin.import_tasks: test.yml
  when: os_test is truthy
