---
#
# Last Changes:
# Wolfgang Hotwagner updated this file on 23. April 2024
#
- name: Make sure opensearch dashboards is started
  ansible.builtin.service:
    name: dashboards
    state: started
    enabled: true

- name: Get all the installed dashboards plugins
  ansible.builtin.command: "sudo -u {{ os_dashboards_user }} {{ os_plugin_bin_path }} list"
  register: list_plugins

- name: Show all the installed dashboards plugins
  ansible.builtin.debug:
    msg: "{{ list_plugins.stdout }}"
